In [32]:
import pandas as pd
import numpy as np
import numpy.linalg as la

df = pd.read_excel(r'C:\Users\year3\Downloads\Lab Session Data.xlsx')
df = df.dropna(axis = 1)
df


Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs)
0      C_1           20             6                 2           386
1      C_2           16             3                 6           289
2      C_3           27             6                 2           393
3      C_4           19             1                 2           110
4      C_5           24             4                 2           280
5      C_6           22             1                 5           167
6      C_7           15             4                 2           271
7      C_8           18             4                 2           274
8      C_9           21             1                 4           148
9     C_10           16             2                 4           198

In [33]:
A = df.iloc[:, 1:-1].values
B =df.iloc[:, -1].values

A = np.array(A)
B = np.array(B)

print("Matrix A :")
print(A)
print("Matrix B :")
print(B)

# number of vectors
noOfVector = A.shape[0]
print('Number of vector is : ', noOfVector)


# Dimensionality
DimensionalityOfA = A.shape[1]
DimensionalityOfB = A.shape[1]
print("Dimensionality of A is" , DimensionalityOfA)
print("Dimensionality of B is" , DimensionalityOfB)

Matrix A :
[[20  6  2]
 [16  3  6]
 [27  6  2]
 [19  1  2]
 [24  4  2]
 [22  1  5]
 [15  4  2]
 [18  4  2]
 [21  1  4]
 [16  2  4]]
Matrix B :
[386 289 393 110 280 167 271 274 148 198]
Number of vector is :  10
Dimensionality of A is 3
Dimensionality of B is 3


In [28]:
# Using Pseudo-Inverse find the cost of each product available for sale.
# (Suggestion: If you use Python, you can use numpy.linalg.pinv() function to get a
# pseudo-inverse.)

pseudoInverse = np.linalg.pinv(A)
priceOfEachProduct = pseudoInverse.dot(B)
priceOfEachProduct = np.array(priceOfEachProduct)
print(priceOfEachProduct)

[ 1. 55. 18.]


In [19]:

# . Use the Pseudo-inverse to calculate the model vector X for predicting the cost of the products
# available with the vendor.

X = np.dot(pseudoInverse, B)
print(X)

[ 1. 55. 18.]


In [20]:

# Mark all customers (in “Purchase Data” table) with payments above Rs. 200 as RICH and others
# as POOR. Develop a classifier model to categorize customers into RICH or POOR class based on
# purchase behavior.

df['Category'] = df['Payment (Rs)'] > 200
df['Category'] = df['Category'].replace({True:'Rich', False:'Poor'})

print(df)


  Customer  Candies (#)  Mangoes (Kg)  Milk Packets (#)  Payment (Rs) Category
0      C_1           20             6                 2           386     Rich
1      C_2           16             3                 6           289     Rich
2      C_3           27             6                 2           393     Rich
3      C_4           19             1                 2           110     Poor
4      C_5           24             4                 2           280     Rich
5      C_6           22             1                 5           167     Poor
6      C_7           15             4                 2           271     Rich
7      C_8           18             4                 2           274     Rich
8      C_9           21             1                 4           148     Poor
9     C_10           16             2                 4           198     Poor


In [27]:
# Please refer to the data present in “IRCTC Stock Price” data sheet of the above excel file. Do the
# following after loading the data to your programming platform.

irctc_data = pd.read_excel(r'C:\Users\year3\Downloads\Lab Session Data.xlsx', sheet_name = 'IRCTC Stock Price')
irctc_data = irctc_data.dropna(axis=1)
print(irctc_data)

             Date Month  Day    Price     Open     High      Low   Volume  \
0    Jun 29, 2021   Jun  Tue  2081.85  2092.00  2126.90  2065.05    1.67M   
1    Jun 28, 2021   Jun  Mon  2077.75  2084.00  2112.45  2068.40  707.73K   
2    Jun 25, 2021   Jun  Fri  2068.85  2084.35  2088.50  2053.10  475.82K   
3    Jun 24, 2021   Jun  Thu  2072.95  2098.00  2098.00  2066.00  541.51K   
4    Jun 23, 2021   Jun  Wed  2078.25  2102.00  2111.40  2072.00  809.62K   
..            ...   ...  ...      ...      ...      ...      ...      ...   
244  Jul 07, 2020   Jul  Tue  1397.40  1410.00  1411.00  1390.05  480.21K   
245  Jul 06, 2020   Jul  Mon  1400.75  1405.50  1415.50  1394.00  614.93K   
246  Jul 03, 2020   Jul  Fri  1405.10  1415.00  1425.00  1398.00  599.49K   
247  Jul 02, 2020   Jul  Thu  1412.35  1440.00  1467.80  1395.30    2.16M   
248  Jul 01, 2020   Jul  Wed  1363.05  1363.65  1377.00  1356.00  383.00K   

       Chg%  
0    0.0020  
1    0.0043  
2   -0.0020  
3   -0.0026  
4   -